# Telegram Bot
TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID_HERE"

# Portals Auth
PORTALS_AUTH_TOKEN = "YOUR_AUTH_TOKEN_HERE"

# Settings
MIN_PROFIT_PERCENT = 10
MAX_PRICE_TON = 5000
SCAN_INTERVAL_SECONDS = 3

# Database
DATABASE_PATH = "nft_bot.db"
